channels:
  - conda-forge
  - ilastik-forge
  - nodefaults
dependencies:
  - python 3.11.*
  - ilastik-core
  - pyqt5-sip !=12.9.0,!=12.13.0
  - qimage2ndarray
  - pyqtgraph
  - conda-build
  - pytest >4
  - pytest-qt
  - pytest-cov
