clone_folder: c:\projects\volumina

environment:
  ENV_NAME: test-env
  # set miniconda version explicitly
  MINICONDA: C:\Miniconda36-x64

install:
  - set "PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c conda-forge conda-build
  - cd \
  # Get the current master of all submodules
  - git clone https://github.com/ilastik/ilastik-meta c:\ilastik\ilastik-meta
  - cd ilastik\ilastik-meta
  - git submodule update --init --recursive
  - git submodule foreach "git checkout master"
  - ps: rm -Force -Recurse c:\ilastik\ilastik-meta\volumina
  - timeout 10
  # replace with whatever version of volumina triggered the appveyor
  - ps: cp -recurse C:\projects\volumina c:\ilastik\ilastik-meta\volumina
  - timeout 10
  - python ilastik/scripts/devenv.py create -n %ENV_NAME% -c ilastik-forge conda-forge -p ilastik-dependencies-no-solvers

build: off

test_script:
  - set "PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - call activate %ENV_NAME%
  - cd \
  - cd ilastik\ilastik-meta\volumina
  - >
      pytest
      --capture=no
      --junitxml=coveralls.xml

# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
